### ISSUE TITLE
problem validating my DateField

### ISSUE THREAD

**Issue by texyh** [brutus/wtforms-html5#1]
i have a datefield in my web application, i used wtf-html5 to create the form
But form.validate always returns false.
here is my snippet
app/forms.py

```
class ProfileForm(Form):
    entrydate = DateField(
        'entrydate',
        format = '%d%m%Y'
    )
```

app/views.py

```
@app.route('/profile', methods = ['GET','POST'])
def profile():
    if request.method == 'POST':
        if form.validate():
            return form.entrydate.data 
        return 'bad form'
    return render_template('profile.html',form=form)
```

it keeps returning bad form

**Comment by brutus** [comment]
Thanks for reporting. I haven't used _wtforms-html_ in some time and a lot of things have changed in _wtforms_ in the meantime. Will have a look at it early next week.

**Comment by brutus** [comment]
I'm sorry, but I can not reproduce your error. 

If I ran the following, the `validate` method always returns `True`:

```
from wtforms import Form
from wtforms_html5 import DateField


class TestForm(Form):
  test_date = DateField('entrydate', format='%d%m%Y')


form = TestForm()
if form.validate():
  print("form validates okay")
else:
  print("form don't validates")
```

Maybe you could try the same with only vanilla [wtforms](https://github.com/wtforms/wtforms) and see if `validate` still returns `False`?

**Comment by brutus** [comment]
I'm sorry, but I can not reproduce your error. 

If I ran the following, the `validate` method always returns `True`:

```
from wtforms import Form
from wtforms_html5 import DateField


class TestForm(Form):
  test_date = DateField('entrydate', format='%d%m%Y')


form = TestForm()
if form.validate():
  print("form validates okay")
else:
  print("form don't validates")
```

Maybe you could try the same with only vanilla [wtforms](https://github.com/wtforms/wtforms) and see if `validate` still returns `False`?

**Comment by brutus** [comment]
Still having this error? I'm inclined to _close_ this in a couple of days if no updated pop up.

BTW: just released a new version, that uses the meta class feature of the current WTForms — maybe give it a try.

**Comment by texyh** [comment]
Kk, am nt getting d error for datefield, trying to workout timefiels now

**Comment by brutus** [comment]
BTW: I just released a new version, dropping all the fields and widgets, cause they are included in new versions of WTForms (see the README for more information). You can get the HTML5 from vanilla WTForms like this:

```py
from wtforms.fields.html5 import EmailField
```
