### ISSUE TITLE
Can I pick seconds with DateTimeLocalField?

### ISSUE THREAD

**Issue by ChunYuan0930** [brutus/wtforms-html5#7]
I'm use DateTimeLocalField with my code,I only can choose date,hours and minutes.
How could I do to add seconds field?

![front-DateTimeLocalField](https://user-images.githubusercontent.com/19742889/70859365-3926ac00-1f4d-11ea-884b-75d8e2e5bbd4.png)

**Comment by brutus** [comment]
Hi. This project just provides a wrapper for [WTForms](https://wtforms.readthedocs.io/). You might hvae a better chance to get your answer from the original project: https://github.com/wtforms/wtforms
