### ISSUE TITLE
running setup.cfg gives syntex error

### ISSUE THREAD

**Issue by gozeen** [brutus/wtforms-html5#70]
i am installing the packeg on my raspi, i cloned the repository.
 when i run setup.cfg it just goes side ways

File "/home/pi/wtforms-html5/setup.cfg", line 3
    version = 0.4.0
                      ^
SyntaxError: invalid syntax

**Comment by brutus** [comment]
The PyPI package was lacking behind, but I updated it to the latest release, so a `pip install --user wtforms-html5` should do fine - does it work for you?

If you cloned the repo, an install should also work via `pip install --user /path/to/repo`; sorry, I'm not sure what you mean by _"running setup.cfg"_.
